---
# tasks file for Oracle
- name: configure swap in /etc/waagent.conf  file
  blockinfile:
    path: /etc/waagent.conf 
    block: |
      ResourceDisk.Format=y
      ResourceDisk.EnableSwap=y
      ResourceDisk.SwapSizeMB="{{Swap_Size}}"
    backup: yes
  register: waagent_info
  
- debug:
    msg: "{{waagent_info}}"  

- name: Restart the waagent service
  service:
    name: waagent
    state: restarted
  when:  waagent_info.changed


- name: Enabled rhel-7-server-rhui-optional-rpms repo
  template:
    src: rh-cloud-repo.j2
    dest: /etc/yum.repos.d/rh-cloud.repo
    owner: root
    group: root
    mode: '0644'
    backup: yes

- name: Oracle 19c RDBMS Preinstall RPMs
  yum:
    name: https://yum.oracle.com/repo/OracleLinux/OL7/latest/x86_64/getPackage/oracle-database-preinstall-19c-1.0-1.el7.x86_64.rpm
    state: present

- name: stat check for /etc/security/limits.d/oracle-database-preinstall-19c.conf  file
  stat:
    path: /etc/security/limits.d/oracle-database-preinstall-19c.conf
  register: preinstall_stat
  
- name: renname the file from  /etc/security/limits.d/oracle-database-preinstall-19c.conf  to /etc/security/limits.d/00-oracle-database-preinstall-19c.conf
  command: mv /etc/security/limits.d/oracle-database-preinstall-19c.conf /etc/security/limits.d/00-oracle-database-preinstall-19c.conf
  when: preinstall_stat.stat.exists



  
    

