---
# tasks file for Oracle
- name: configure swap in /etc/waagent.conf  file
  blockinfile:
    path: /etc/waagent.conf 
    block: |
      ResourceDisk.Format=y
      ResourceDisk.EnableSwap=y
      ResourceDisk.SwapSizeMB="{{Swap_Size}}"
    backup: yes
    register: waagent_info

- debug:
    msg: "{{waagent_info}}"  

- name: Restart the waagent service
  service:
    name: waagent
    state: restarted
    
