---
# tasks file for Oracle
- name: configure swap in /etc/waagent.conf  file
  blockinfile:
    path: /etc/waagent.conf 
    block: |
      ResourceDisk.Format=y
      ResourceDisk.EnableSwap=y
      ResourceDisk.SwapSizeMB="{{Swap_Size}}"
    backup: yes
  register: waagent_info
  
- debug:
    msg: "{{waagent_info}}"  

- name: Restart the waagent service
  service:
    name: waagent
    state: restarted
  when:  waagent_info.changed
    
- name: update rh-cloud.repo repo
  shell:
    cmd: yum-config-manager --enable rhel-7-server-rhui-optional-rpms
- name: install oracle pre-requiste package
  yum:
    name: https://yum.oracle.com/repo/OracleLinux/OL7/latest/x86_64/getPackage/oracle-database-preinstall-19c-1.0-1.el7.x86_64.rpm
    state: present
  register: oracle-prerequiste
- debug:
    msg: "{{prerequiste}}"
