---
# tasks file for Oracle
- name: configure swap in /etc/waagent.conf  file
  blockinfile:
    path: /etc/waagent.conf 
    block: |
      ResourceDisk.Format=y
      ResourceDisk.EnableSwap=y
      ResourceDisk.SwapSizeMB="{{Swap_Size}}"
    backup: yes
  register: waagent_info
  
- debug:
    msg: "{{waagent_info}}"  

- name: Restart the waagent service
  service:
    name: waagent
    state: restarted
  when:  waagent_info.changed
    
- name: update rh-cloud.repo repo
  lineinfile:
    path: /etc/yum.repos.d/rh-cloud.repo
    regexp: '^enabled'
    insertafter: https://rhui-3.microsoft.com/pulp/repos//content/dist/rhel/rhui/server/7/$releasever/$basearch/optional/os
    line: enabled=0